// <auto-generated />
using System;
using AIStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918081522_AddSubtitleTracks")]
    partial class AddSubtitleTracks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIStudio.Domain.Assets.SceneAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Creator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("creator");

                    b.Property<string>("License")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset?>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<int>("SceneIndex")
                        .HasColumnType("integer")
                        .HasColumnName("scene_index");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<Guid>("SourceJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_job_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SourceJobId")
                        .HasDatabaseName("ix_scene_assets_source_job_id");

                    b.HasIndex("ContentProjectId", "SceneIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_scene_assets_content_project_scene");

                    b.ToTable("scene_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_scene_assets_byte_size", "byte_size >= 0");

                            t.HasCheckConstraint("ck_scene_assets_content_hash", "char_length(content_hash) = 64");

                            t.HasCheckConstraint("ck_scene_assets_scene_index", "scene_index >= 0");
                        });
                });

            modelBuilder.Entity("AIStudio.Domain.Content.ContentProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brief")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("brief");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_content_projects_status");

                    b.ToTable("content_projects", (string)null);
                });

            modelBuilder.Entity("AIStudio.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_summary");

                    b.Property<string>("InputVersionHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_version_hash");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId")
                        .HasDatabaseName("ix_jobs_content_project_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_jobs_status_created_at");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_max_retries", "max_retries >= 0 AND max_retries <= 10");

                            t.HasCheckConstraint("ck_jobs_retry_allowance", "retry_count <= max_retries");

                            t.HasCheckConstraint("ck_jobs_retry_count", "retry_count >= 0");
                        });
                });

            modelBuilder.Entity("AIStudio.Domain.Narration.NarrationTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Creator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("creator");

                    b.Property<string>("License")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset?>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<Guid>("SourceJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_job_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_narration_tracks_content_project_id");

                    b.HasIndex("SourceJobId")
                        .HasDatabaseName("ix_narration_tracks_source_job_id");

                    b.ToTable("narration_tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_narration_tracks_byte_size", "byte_size >= 0");

                            t.HasCheckConstraint("ck_narration_tracks_content_hash", "char_length(content_hash) = 64");
                        });
                });

            modelBuilder.Entity("AIStudio.Domain.Scripts.ReviewedScript", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("SourceJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviewed_scripts_content_project_id");

                    b.HasIndex("SourceJobId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviewed_scripts_source_job_id");

                    b.ToTable("reviewed_scripts", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviewed_scripts_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("AIStudio.Domain.Subtitles.SubtitleTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<Guid>("ContentProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Creator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("creator");

                    b.Property<string>("License")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset?>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<Guid>("SourceJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_job_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_subtitle_tracks_content_project_id");

                    b.HasIndex("SourceJobId")
                        .HasDatabaseName("ix_subtitle_tracks_source_job_id");

                    b.ToTable("subtitle_tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_subtitle_tracks_byte_size", "byte_size >= 0");

                            t.HasCheckConstraint("ck_subtitle_tracks_content_hash", "char_length(content_hash) = 64");
                        });
                });

            modelBuilder.Entity("AIStudio.Domain.Assets.SceneAsset", b =>
                {
                    b.HasOne("AIStudio.Domain.Content.ContentProject", "ContentProject")
                        .WithMany()
                        .HasForeignKey("ContentProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIStudio.Domain.Jobs.Job", "SourceJob")
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentProject");

                    b.Navigation("SourceJob");
                });

            modelBuilder.Entity("AIStudio.Domain.Jobs.Job", b =>
                {
                    b.HasOne("AIStudio.Domain.Content.ContentProject", "ContentProject")
                        .WithMany()
                        .HasForeignKey("ContentProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentProject");
                });

            modelBuilder.Entity("AIStudio.Domain.Narration.NarrationTrack", b =>
                {
                    b.HasOne("AIStudio.Domain.Content.ContentProject", "ContentProject")
                        .WithMany()
                        .HasForeignKey("ContentProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIStudio.Domain.Jobs.Job", "SourceJob")
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentProject");

                    b.Navigation("SourceJob");
                });

            modelBuilder.Entity("AIStudio.Domain.Scripts.ReviewedScript", b =>
                {
                    b.HasOne("AIStudio.Domain.Content.ContentProject", "ContentProject")
                        .WithMany()
                        .HasForeignKey("ContentProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIStudio.Domain.Jobs.Job", "SourceJob")
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentProject");

                    b.Navigation("SourceJob");
                });

            modelBuilder.Entity("AIStudio.Domain.Subtitles.SubtitleTrack", b =>
                {
                    b.HasOne("AIStudio.Domain.Content.ContentProject", "ContentProject")
                        .WithMany()
                        .HasForeignKey("ContentProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIStudio.Domain.Jobs.Job", "SourceJob")
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentProject");

                    b.Navigation("SourceJob");
                });
#pragma warning restore 612, 618
        }
    }
}
