namespace AIStudio.Application.Assets;

public interface IAssetFileStore
{
    AssetFileInfo Register(string relativePath);

    /// <summary>
    /// Writes generated bytes under the approved asset root and returns canonical
    /// metadata. Writing identical content to an existing file is a no-op, so
    /// regeneration is idempotent.
    /// </summary>
    Task<AssetFileInfo> WriteAsync(
        string relativePath,
        byte[] content,
        CancellationToken cancellationToken);
}

public sealed record AssetFileInfo(
    string RelativePath,
    string AbsolutePath,
    long ByteSize,
    string ContentHash);
