using System.Text.Json.Serialization;
using AIStudio.Application.Bibles;
using AIStudio.Application.Concepts;
using AIStudio.Application.Creative;
using AIStudio.Application.Stories;

namespace AIStudio.Application.StoryContext;

/// <summary>
/// A compact, consumer-neutral projection of the trusted narrative inputs for one
/// story: the creative direction, the story plan, and only the character/world
/// identity the story actually references. It is produced deterministically by
/// <c>StoryContextBuilder</c> for future Script and Storyboard consumers. It contains
/// declarative narrative data only — no prompt text, provider detail, path, or
/// executable instruction — and it is not generated by a model.
/// </summary>
public sealed record StoryContext
{
    [JsonPropertyName("concept")]
    public StoryConceptContext Concept { get; init; } = new();

    /// <summary>The creative treatment, reused as-is (not duplicated).</summary>
    [JsonPropertyName("treatment")]
    public CreativeTreatment Treatment { get; init; } = new();

    [JsonPropertyName("story")]
    public StoryNarrativeContext Story { get; init; } = new();

    /// <summary>Only characters referenced by the projected beats, ordered by id.</summary>
    [JsonPropertyName("characters")]
    public IReadOnlyList<StoryCharacterContext> Characters { get; init; } = [];

    /// <summary>Only worlds referenced by the projected beats, ordered by id.</summary>
    [JsonPropertyName("worlds")]
    public IReadOnlyList<StoryWorldContext> Worlds { get; init; } = [];

    /// <summary>Projected beats in order; one beat for a beat-scoped context.</summary>
    [JsonPropertyName("beats")]
    public IReadOnlyList<StoryBeatContext> Beats { get; init; } = [];

    /// <summary>Optional caller-supplied mutable state, projected separately from identity.</summary>
    [JsonPropertyName("states")]
    public StoryStateContext? States { get; init; }

    /// <summary>The requested beat when this is a beat-scoped context; otherwise null.</summary>
    [JsonPropertyName("beatScope")]
    public StoryBeatId? BeatScope { get; init; }
}

/// <summary>
/// The compact concept portion of the context: what the story is about and for whom.
/// It deliberately omits registry internals (recipe id, tags) and description, so a
/// downstream consumer only sees storytelling-relevant fields.
/// </summary>
public sealed record StoryConceptContext
{
    [JsonPropertyName("id")]
    public ConceptId Id { get; init; }

    [JsonPropertyName("title")]
    public string Title { get; init; } = string.Empty;

    [JsonPropertyName("audience")]
    public string Audience { get; init; } = string.Empty;

    [JsonPropertyName("format")]
    public string Format { get; init; } = string.Empty;

    [JsonPropertyName("style")]
    public string Style { get; init; } = string.Empty;

    [JsonPropertyName("duration")]
    public int Duration { get; init; }
}

/// <summary>The structural shape of the story: which narrative pattern it follows and its target length.</summary>
public sealed record StoryNarrativeContext
{
    [JsonPropertyName("id")]
    public StoryPlanId Id { get; init; }

    [JsonPropertyName("version")]
    public int Version { get; init; }

    [JsonPropertyName("pattern")]
    public NarrativePatternId Pattern { get; init; }

    [JsonPropertyName("patternVersion")]
    public NarrativePatternVersion PatternVersion { get; init; }

    [JsonPropertyName("targetDuration")]
    public int TargetDurationSeconds { get; init; }
}

/// <summary>
/// One projected beat: the narrative progression step a downstream consumer needs.
/// It carries purpose and continuity references only — no dialogue, camera, engine,
/// prompt, or executable instruction.
/// </summary>
public sealed record StoryBeatContext
{
    [JsonPropertyName("id")]
    public StoryBeatId Id { get; init; }

    [JsonPropertyName("order")]
    public int Order { get; init; }

    [JsonPropertyName("role")]
    public StoryBeatRole Role { get; init; }

    [JsonPropertyName("purpose")]
    public string Purpose { get; init; } = string.Empty;

    [JsonPropertyName("importance")]
    public string Importance { get; init; } = StoryBeat.DefaultImportance;

    [JsonPropertyName("durationSeconds")]
    public int DurationSeconds { get; init; }

    [JsonPropertyName("characterRefs")]
    public IReadOnlyList<string> CharacterRefs { get; init; } = [];

    [JsonPropertyName("worldRefs")]
    public IReadOnlyList<string> WorldRefs { get; init; } = [];

    [JsonPropertyName("continuityFrom")]
    public IReadOnlyList<StoryBeatId> ContinuityFrom { get; init; } = [];
}

/// <summary>
/// Optional caller-supplied mutable scene state, kept separate from stable identity.
/// A character/world bible describes what stays recognizable; these describe what may
/// change per scene. v1 does not interpret or merge state into identity.
/// </summary>
public sealed record StoryStateContext
{
    [JsonPropertyName("characters")]
    public IReadOnlyList<CharacterState> Characters { get; init; } = [];

    [JsonPropertyName("worlds")]
    public IReadOnlyList<WorldState> Worlds { get; init; } = [];
}
