<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AIStudio.CreativeValidation</RootNamespace>
    <AssemblyName>AIStudio.CreativeValidation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AIStudio.Infrastructure\AIStudio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
